apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rx2icvlnf-nodejs 
  janus-idp.io/tekton: rx2icvlnf-nodejs
  backstage.io/kubernetes-id: rx2icvlnf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rx2icvlnf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml