apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rx2icvlnf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rx2icvlnf-nodejs 
  name: rx2icvlnf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rx2icvlnf-nodejs 
